n = input('Digite algo: ')
print('O seu tipo primitivo é: {}'.format(type))
print('Só possui espaços: {}'.format(n.isspace()))
print('É um número? {}'.format(n.isnumeric()))
print('É alfabético? {}'.format(n.isalpha()))
print('É alfanúmerico? {}'.format(n.isalnum()))
print('Está em maiúscula? {}'.format(n.isupper()))
print('Está em minúscula? {}'.format(n.islower()))
print('Está capitalizada? {}'.format(n.istitle()))
